backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/upload" # Where media files will be stored
public_folder: "/upload" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Instagram"
            name: "instagram"
            widget: "string"
          - label: "LinkedIn"
            name: "linkedin"
            widget: "string"
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/home.yml"
        fields:
          - {label: Marquee, name: marquee, widget: string}
          - label: "Desktop images"
            name: "desktopImages"
            widget: "list"
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image, required: true}
          - label: "Mobile images"
            name: "mobileImages"
            widget: "list"
            summary: '{{fields.image}}'
            field: {label: Image, name: image, widget: image, required: true}